"""Gemini-backed summary generation."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import TYPE_CHECKING

from app.backend.llm.egress import DataEgressDisabledError
from app.backend.llm.usage import log_usage
from app.backend.summarization.generators import CandidateCitation, CandidateSummarySentence, SourceChunk

if TYPE_CHECKING:
    from sqlalchemy import Connection

# Bumped whenever ``_prompt`` OR the default model changes — it's part of the summary cache key
# (app/backend/llm/cache.py via ``cache_signature``), so editing the prompt can never serve a cached
# output generated by the old prompt.
SUMMARY_PROMPT_VERSION = "summary-v1"

# ``DataEgressDisabledError`` is re-exported (its canonical home is app/backend/llm/egress.py) so the
# provider self-checks below and the existing `from integrations.gemini import DataEgressDisabledError`
# imports keep resolving unchanged.
__all__ = ["DataEgressDisabledError", "GeminiConfig", "LLMConfig", "GeminiSummaryGenerator"]

# Per-provider default models (inc 149). `local` has no default — the user names their own model.
DEFAULT_MODELS = {
    "gemini": "gemini-2.5-flash-lite",
    "openai": "gpt-4o-mini",
    "anthropic": "claude-3-5-haiku-latest",
    "local": "",
}


@dataclass(frozen=True)
class LLMConfig:
    """Provider-neutral LLM config (inc 149). `provider` ∈ gemini/openai/anthropic/local; `api_key` is the
    ACTIVE provider's resolved key; `base_url` is the loopback endpoint for the local provider. The generators
    route every call through ``app.backend.llm.providers.complete(config, prompt)``."""

    model: str = "gemini-2.5-flash-lite"
    api_key_env: str = "GOOGLE_API_KEY"
    api_key: str | None = None
    provider: str = "gemini"
    base_url: str | None = None  # the local (OpenAI-compatible) endpoint
    data_egress_enabled: bool = False
    help_assistant_enabled: bool = False

    @classmethod
    def from_environment(cls) -> "LLMConfig":
        # BYOK (inc 146/149): the Settings UI stores the provider + per-provider key + egress consent in a local
        # file; when present, the stored value OVERLAYS the env default (env stays the fallback). Lazy import keeps
        # integrations/ loosely coupled to app.backend.
        from app.backend.app_settings import load_settings

        stored = load_settings()
        provider = stored.get("provider")
        if provider not in {"gemini", "openai", "anthropic", "local"}:
            provider = "gemini"
        env_egress = os.getenv("CALLOSUM_ALLOW_DATA_EGRESS", "").strip().lower() in {"1", "true", "yes"}
        stored_egress = stored.get("data_egress_enabled")
        enabled = stored_egress if isinstance(stored_egress, bool) else env_egress
        # The help assistant has its OWN, independent toggle: it sends only the user's question + the public
        # help docs (never library text), so it must NOT be gated by the library data-egress flag above.
        help_enabled = os.getenv("CALLOSUM_HELP_ASSISTANT_ENABLED", "").strip().lower() in {"1", "true", "yes"}
        model = (stored.get("model") or "").strip() or DEFAULT_MODELS.get(provider, DEFAULT_MODELS["gemini"])
        base_url = (stored.get("local_base_url") or "").strip() or None
        return cls(
            provider=provider,
            model=model,
            api_key=_resolve_key(provider, stored),
            base_url=base_url,
            data_egress_enabled=enabled,
            help_assistant_enabled=help_enabled,
        )

    def resolved_api_key(self) -> str | None:
        # The active provider's key. The GOOGLE_API_KEY env fallback applies only to gemini (the others have no
        # env fallback baked into a directly-constructed config; from_environment resolves their stored keys).
        return self.api_key or (os.getenv(self.api_key_env) if self.provider == "gemini" else None)


def _resolve_key(provider: str, stored: dict) -> str | None:
    def _s(v: object) -> str | None:
        return v if isinstance(v, str) and v.strip() else None

    if provider == "gemini":
        return _s(stored.get("api_key")) or os.getenv("GOOGLE_API_KEY")  # inc-146 key stored under "api_key"
    if provider == "openai":
        return _s(stored.get("openai_api_key")) or os.getenv("OPENAI_API_KEY")
    if provider == "anthropic":
        return _s(stored.get("anthropic_api_key")) or os.getenv("ANTHROPIC_API_KEY")
    return _s(stored.get("local_api_key"))  # local: usually none (a loopback server)


# Back-compat alias: the config is multi-provider now, but ~12 call sites import ``GeminiConfig``.
GeminiConfig = LLMConfig


@dataclass(frozen=True)
class GeminiSummaryGenerator:
    config: GeminiConfig
    name: str = "gemini-summary-generator"

    @property
    def cache_signature(self) -> str:
        """Identity for the content-addressed cache key: model + prompt-template version."""
        return f"{self.name}/{self.config.model}/{SUMMARY_PROMPT_VERSION}"

    def generate(
        self,
        *,
        source_chunks: list[SourceChunk],
        scope_ref: dict[str, object],
        conn: "Connection | None" = None,  # caching is handled by the wrapper; the provider ignores it
    ) -> list[CandidateSummarySentence]:
        from app.backend.llm.providers import complete, requires_egress

        if requires_egress(self.config.provider) and not self.config.data_egress_enabled:
            raise DataEgressDisabledError("Summary generation requires explicit data-egress consent.")
        result = complete(self.config, _prompt(source_chunks=source_chunks, scope_ref=scope_ref))
        log_usage("summary", self.config.model, result)
        return _parse_response_text(str(result.text or "[]"))


def _prompt(*, source_chunks: list[SourceChunk], scope_ref: dict[str, object]) -> str:
    chunks_json = [
        {
            "chunk_id": chunk.chunk_id,
            "paper_id": chunk.paper_id,
            "page_start": chunk.page_start,
            "page_end": chunk.page_end,
            "text": chunk.text,
        }
        for chunk in source_chunks
    ]
    return (
        "Return JSON only: an array of objects with keys text and citations. "
        "Each citation must contain chunk_id and a verbatim quote from that chunk. "
        "Do not invent citations. Scope: "
        f"{json.dumps(scope_ref, ensure_ascii=True)}\n"
        f"Chunks: {json.dumps(chunks_json, ensure_ascii=True)}"
    )


def _parse_response_text(text: str) -> list[CandidateSummarySentence]:
    payload = json.loads(_strip_code_fence(text))
    sentences = []
    for item in payload:
        citations = [
            CandidateCitation(chunk_id=int(citation["chunk_id"]), quote=str(citation["quote"]))
            for citation in item.get("citations", [])
        ]
        sentences.append(CandidateSummarySentence(text=str(item["text"]), citations=citations))
    return sentences


def _strip_code_fence(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return stripped
