"""Gemini-backed summary generation."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import TYPE_CHECKING

from app.backend.llm.egress import DataEgressDisabledError
from app.backend.llm.usage import log_usage
from app.backend.summarization.generators import CandidateCitation, CandidateSummarySentence, SourceChunk

if TYPE_CHECKING:
    from sqlalchemy import Connection

# Bumped whenever ``_prompt`` OR the default model changes — it's part of the summary cache key
# (app/backend/llm/cache.py via ``cache_signature``), so editing the prompt can never serve a cached
# output generated by the old prompt.
SUMMARY_PROMPT_VERSION = "summary-v1"

# ``DataEgressDisabledError`` is re-exported (its canonical home is app/backend/llm/egress.py) so the
# provider self-checks below and the existing `from integrations.gemini import DataEgressDisabledError`
# imports keep resolving unchanged.
__all__ = ["DataEgressDisabledError", "GeminiConfig", "GeminiSummaryGenerator"]


@dataclass(frozen=True)
class GeminiConfig:
    model: str = "gemini-2.5-flash-lite"
    api_key_env: str = "GOOGLE_API_KEY"
    api_key: str | None = None
    data_egress_enabled: bool = False
    help_assistant_enabled: bool = False

    @classmethod
    def from_environment(cls) -> "GeminiConfig":
        # BYOK (inc 146): the Settings UI can store an API key + egress consent in a local file; when present,
        # the stored value OVERLAYS the env default (env stays the fallback, so existing .env setups are
        # unaffected). Lazy import keeps integrations/ loosely coupled to app.backend.
        from app.backend.app_settings import load_settings

        stored = load_settings()
        env_egress = os.getenv("CALLOSUM_ALLOW_DATA_EGRESS", "").strip().lower() in {"1", "true", "yes"}
        stored_egress = stored.get("data_egress_enabled")
        enabled = stored_egress if isinstance(stored_egress, bool) else env_egress
        # The help assistant has its OWN, independent toggle: it sends only the user's question + the public
        # help docs (never library text), so it must NOT be gated by the library data-egress flag above.
        help_enabled = os.getenv("CALLOSUM_HELP_ASSISTANT_ENABLED", "").strip().lower() in {"1", "true", "yes"}
        stored_key = stored.get("api_key")
        api_key = stored_key if isinstance(stored_key, str) and stored_key.strip() else None
        return cls(data_egress_enabled=enabled, help_assistant_enabled=help_enabled, api_key=api_key)

    def resolved_api_key(self) -> str | None:
        return self.api_key or os.getenv(self.api_key_env)


@dataclass(frozen=True)
class GeminiSummaryGenerator:
    config: GeminiConfig
    name: str = "gemini-summary-generator"

    @property
    def cache_signature(self) -> str:
        """Identity for the content-addressed cache key: model + prompt-template version."""
        return f"{self.name}/{self.config.model}/{SUMMARY_PROMPT_VERSION}"

    def generate(
        self,
        *,
        source_chunks: list[SourceChunk],
        scope_ref: dict[str, object],
        conn: "Connection | None" = None,  # caching is handled by the wrapper; the provider ignores it
    ) -> list[CandidateSummarySentence]:
        if not self.config.data_egress_enabled:
            raise DataEgressDisabledError("Gemini summary generation requires explicit data-egress consent.")

        from google import genai

        client = genai.Client(api_key=self.config.resolved_api_key())
        response = client.models.generate_content(
            model=self.config.model,
            contents=_prompt(source_chunks=source_chunks, scope_ref=scope_ref),
        )
        log_usage("summary", self.config.model, response)
        return _parse_response_text(str(response.text or "[]"))


def _prompt(*, source_chunks: list[SourceChunk], scope_ref: dict[str, object]) -> str:
    chunks_json = [
        {
            "chunk_id": chunk.chunk_id,
            "paper_id": chunk.paper_id,
            "page_start": chunk.page_start,
            "page_end": chunk.page_end,
            "text": chunk.text,
        }
        for chunk in source_chunks
    ]
    return (
        "Return JSON only: an array of objects with keys text and citations. "
        "Each citation must contain chunk_id and a verbatim quote from that chunk. "
        "Do not invent citations. Scope: "
        f"{json.dumps(scope_ref, ensure_ascii=True)}\n"
        f"Chunks: {json.dumps(chunks_json, ensure_ascii=True)}"
    )


def _parse_response_text(text: str) -> list[CandidateSummarySentence]:
    payload = json.loads(_strip_code_fence(text))
    sentences = []
    for item in payload:
        citations = [
            CandidateCitation(chunk_id=int(citation["chunk_id"]), quote=str(citation["quote"]))
            for citation in item.get("citations", [])
        ]
        sentences.append(CandidateSummarySentence(text=str(item["text"]), citations=citations))
    return sentences


def _strip_code_fence(text: str) -> str:
    stripped = text.strip()
    if stripped.startswith("```"):
        lines = stripped.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        return "\n".join(lines).strip()
    return stripped
