"""Schema owned by the registration-reference/comparison workflow."""

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Table,
    Text,
    UniqueConstraint,
    func,
)

from app.backend.persistence.schema_base import metadata

paper_registration_references = Table(
    "paper_registration_references",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("paper_id", ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
    Column("attachment_id", ForeignKey("attachments.id", ondelete="CASCADE")),
    Column("provider", String(100), nullable=False),
    Column("external_id", String(500), nullable=False),
    Column("canonical_url", Text),
    Column("visible_text", Text),
    Column("evidence_snippet", Text),
    Column("page", Integer),
    Column("extraction_method", String(100), nullable=False),
    Column("evidence_class", String(100), nullable=False),
    Column("explicitly_printed", Boolean, nullable=False, server_default="0"),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint(
        "paper_id",
        "attachment_id",
        "provider",
        "external_id",
        "extraction_method",
        name="uq_registration_reference_source",
    ),
    CheckConstraint("page IS NULL OR page >= 1", name="registration_reference_page_positive"),
    Index("ix_registration_references_paper_id", "paper_id"),
    Index("ix_registration_references_attachment_id", "attachment_id"),
)

paper_registration_links = Table(
    "paper_registration_links",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("paper_id", ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
    Column("attachment_id", ForeignKey("attachments.id", ondelete="SET NULL")),
    Column("provider", String(100), nullable=False),
    Column("external_id", String(500), nullable=False),
    Column("registration_doi", String(500)),
    Column("canonical_url", Text),
    Column("title", Text),
    Column("contributors_json", JSON),
    Column("registered_at", String(100)),
    Column("registration_status", String(100)),
    Column("schema_name", Text),
    Column("link_status", String(30), nullable=False, server_default="candidate"),
    Column("linkage_class", String(50), nullable=False),
    Column("match_method", String(100), nullable=False),
    Column("match_evidence_json", JSON, nullable=False),
    Column("user_confirmed", Boolean, nullable=False, server_default="0"),
    Column("source_metadata_json", JSON),
    Column("content_hash", String(128)),
    Column("retrieved_at", DateTime),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint("paper_id", "provider", "external_id", name="uq_paper_registration_link_candidate"),
    CheckConstraint(
        "link_status IN ('candidate','confirmed','rejected','unavailable','withdrawn')",
        name="registration_link_status_valid",
    ),
    CheckConstraint(
        "linkage_class IN ('explicit-linkage','strong-contextual-match','similarity-candidate')",
        name="registration_linkage_class_valid",
    ),
    Index("ix_registration_links_paper_status", "paper_id", "link_status"),
    Index("ix_registration_links_external", "provider", "external_id"),
)

registration_document_versions = Table(
    "registration_document_versions",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("link_id", ForeignKey("paper_registration_links.id", ondelete="CASCADE"), nullable=False),
    Column("paper_id", ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
    Column("attachment_id", ForeignKey("attachments.id", ondelete="SET NULL")),
    Column("provider", String(100), nullable=False),
    Column("external_id", String(500), nullable=False),
    Column("content_hash", String(128), nullable=False),
    Column("canonical_url", Text),
    Column("registered_at", String(100)),
    Column("registration_status", String(100)),
    Column("schema_name", Text),
    Column("schema_version", String(100)),
    Column("structured_json", JSON, nullable=False),
    Column("rendered_text", Text),
    Column("source_metadata_json", JSON, nullable=False),
    Column("retrieved_at", DateTime, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint("link_id", "content_hash", name="uq_registration_document_version_hash"),
    Index("ix_registration_versions_paper_id", "paper_id"),
    Index("ix_registration_versions_link_id", "link_id"),
)

registration_commitments = Table(
    "registration_commitments",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("version_id", ForeignKey("registration_document_versions.id", ondelete="CASCADE"), nullable=False),
    Column("paper_id", ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
    Column("link_id", ForeignKey("paper_registration_links.id", ondelete="CASCADE"), nullable=False),
    Column("attachment_id", ForeignKey("attachments.id", ondelete="SET NULL")),
    Column("field_type", String(100), nullable=False),
    Column("study_label", Text),
    Column("ordinal", Integer, nullable=False),
    Column("structured_value_json", JSON, nullable=False),
    Column("evidence_text", Text, nullable=False),
    Column("source_section", Text),
    Column("source_key", String(500), nullable=False),
    Column("page", Integer),
    Column("chunk_id", ForeignKey("chunks.id", ondelete="SET NULL")),
    Column("source_locator_json", JSON, nullable=False),
    Column("extraction_method", String(100), nullable=False),
    Column("extraction_confidence", String(30), nullable=False),
    Column("registration_content_hash", String(128), nullable=False),
    Column("extraction_version", String(100), nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    UniqueConstraint(
        "version_id",
        "field_type",
        "source_key",
        "extraction_version",
        name="uq_registration_commitment_source",
    ),
    CheckConstraint("ordinal >= 0", name="registration_commitment_ordinal_nonnegative"),
    CheckConstraint("page IS NULL OR page >= 1", name="registration_commitment_page_positive"),
    CheckConstraint(
        "extraction_confidence IN ('high','medium','low')",
        name="registration_commitment_confidence_valid",
    ),
    Index("ix_registration_commitments_version", "version_id", "ordinal"),
    Index("ix_registration_commitments_paper", "paper_id", "field_type"),
)

registration_comparison_runs = Table(
    "registration_comparison_runs",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("paper_id", ForeignKey("papers.id", ondelete="CASCADE"), nullable=False),
    Column("link_id", ForeignKey("paper_registration_links.id", ondelete="CASCADE"), nullable=False),
    Column(
        "registration_version_id", ForeignKey("registration_document_versions.id", ondelete="CASCADE"), nullable=False
    ),
    Column("status", String(30), nullable=False, server_default="completed"),
    Column("registration_content_hash", String(128), nullable=False),
    Column("article_fingerprint", String(128), nullable=False),
    Column("supplement_fingerprint", String(128)),
    Column("article_source_json", JSON, nullable=False),
    Column("supplement_source_json", JSON, nullable=False),
    Column("commitment_extraction_version", String(100), nullable=False),
    Column("retrieval_version", String(100), nullable=False),
    Column("comparison_version", String(100), nullable=False),
    Column("configuration_json", JSON, nullable=False),
    Column("model_versions_json", JSON, nullable=False),
    Column("stale_reasons_json", JSON, nullable=False),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("completed_at", DateTime),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    CheckConstraint("status IN ('completed','stale')", name="registration_comparison_run_status_valid"),
    Index("ix_registration_comparison_runs_paper", "paper_id", "created_at"),
)

registration_comparison_rows = Table(
    "registration_comparison_rows",
    metadata,
    Column("id", Integer, primary_key=True),
    Column("run_id", ForeignKey("registration_comparison_runs.id", ondelete="CASCADE"), nullable=False),
    Column("commitment_id", ForeignKey("registration_commitments.id", ondelete="SET NULL")),
    Column("field_type", String(100), nullable=False),
    Column("registration_value_json", JSON),
    Column("registration_evidence_text", Text),
    Column("registration_source_locator_json", JSON),
    Column("publication_value_json", JSON),
    Column("publication_evidence_text", Text),
    Column("publication_source_locator_json", JSON),
    Column("comparison_status", String(80), nullable=False),
    Column("timing_status", String(100)),
    Column("explanation", Text, nullable=False),
    Column("uncertainty", Text, nullable=False),
    Column("search_scope_json", JSON, nullable=False),
    Column("registration_version_id", Integer, nullable=False),
    Column("registration_content_hash", String(128), nullable=False),
    Column("publication_attachment_id", ForeignKey("attachments.id", ondelete="SET NULL")),
    Column("publication_attachment_checksum", String(128)),
    Column("review_state", String(30), nullable=False, server_default="unreviewed"),
    Column("note", Text),
    Column("created_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    Column("updated_at", DateTime, nullable=False, server_default=func.current_timestamp()),
    CheckConstraint(
        "comparison_status IN ('aligned','potentially-changed','planned-item-not-located-in-publication',"
        "'reported-item-not-located-in-registration','disclosed-deviation','underspecified-in-registration',"
        "'underspecified-in-publication','ambiguous-study-mapping','not-comparable','extraction-uncertain')",
        name="registration_comparison_status_valid",
    ),
    CheckConstraint(
        "review_state IN ('unreviewed','reviewed','dismissed')",
        name="registration_comparison_review_state_valid",
    ),
    Index("ix_registration_comparison_rows_run", "run_id", "id"),
    Index("ix_registration_comparison_rows_review", "review_state", "comparison_status"),
)
