"""Generate the NSIS include that carries connector/identity.json's values into the installer.

NSIS can't parse JSON, so this is the one place identity.json's `native_host_name` and
`production_extension_ids` get turned into NSIS text -- everything else (the Rust connector host,
tests) reads identity.json directly. `installer-hooks.nsh` `!include`s the file this script writes;
nothing in that hand-maintained file repeats these values as a second, driftable copy.

`CONNECTOR_NATIVE_HOST_NAME` is defined WITHOUT wrapping quotes, deliberately: it is interpolated
inside OTHER quoted NSIS strings (the registry key path defines), and a quoted value would leave
stray embedded quote characters in those. `CONNECTOR_WRITE_ALLOWED_ORIGINS_JSON` is a macro, not a
`!define` string, because `allowed_origins` is a JSON ARRAY of arbitrary length (0 today -- see
identity.json's own comment on why) and NSIS's preprocessor has no clean way to hand a `!define`
a multi-element quoted-string list; emitting the exact `FileWrite` calls needed avoids relying on
any NSIS-preprocessor quoting behavior beyond plain text substitution.

The identity is validated first (see `connector_identity.py`): a malformed or duplicated extension id, a
dev id leaking into the production list, or an invalid host name stops the build instead of producing an
installer whose manifest silently allows the wrong callers. An EMPTY production list stays valid here --
whether a given build may ship with none is release policy, decided elsewhere.

Usage: python app/desktop-shell/packaging/generate_connector_nsh.py [--identity PATH] [--out PATH]
(the two flags exist so tests can run the real generator against a synthetic identity without patching it).
"""

from __future__ import annotations

import argparse
from pathlib import Path

from connector_identity import allowed_origins, load_identity, validate_identity

PROJECT_ROOT = Path(__file__).resolve().parents[3]
IDENTITY_PATH = PROJECT_ROOT / "app" / "desktop-shell" / "connector" / "identity.json"
OUT_PATH = PROJECT_ROOT / "app" / "desktop-shell" / "src-tauri" / "windows" / "connector-identity.generated.nsh"


def render(identity: dict) -> str:
    """The generated include's text for an already-validated identity."""
    origins = allowed_origins(identity["production_extension_ids"])
    lines = [
        "; GENERATED by packaging/generate_connector_nsh.py from connector/identity.json.",
        "; Do not hand-edit -- rerun the generator after changing identity.json instead.",
        "",
        f"!define CONNECTOR_NATIVE_HOST_NAME {identity['native_host_name']}",
        "",
        "!macro CONNECTOR_WRITE_ALLOWED_ORIGINS_JSON",
    ]
    if not origins:
        lines.append("  FileWrite $1 '[]$\\r$\\n'")
    else:
        lines.append("  FileWrite $1 '[$\\r$\\n'")
        for index, origin in enumerate(origins):
            comma = "," if index < len(origins) - 1 else ""
            lines.append(f"  FileWrite $1 '    \"{origin}\"{comma}$\\r$\\n'")
        lines.append("  FileWrite $1 '  ]$\\r$\\n'")
    lines.append("!macroend")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--identity", type=Path, default=IDENTITY_PATH)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    args = parser.parse_args(argv)

    identity = load_identity(args.identity)
    problems = validate_identity(identity)
    if problems:
        raise SystemExit("identity.json: " + "; ".join(problems))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(identity), encoding="utf-8")
    print(f"generated {args.out} ({len(identity['production_extension_ids'])} allowed origin(s))")


if __name__ == "__main__":
    main()
