"""Generate the NSIS include that carries connector/identity.json's values into the installer.

NSIS can't parse JSON, so this is the one place identity.json's `native_host_name` and
`production_extension_ids` get turned into NSIS text -- everything else (the Rust connector host,
tests) reads identity.json directly. `installer-hooks.nsh` `!include`s the file this script writes;
nothing in that hand-maintained file repeats these values as a second, driftable copy.

`CONNECTOR_NATIVE_HOST_NAME` is defined WITHOUT wrapping quotes, deliberately: it is interpolated
inside OTHER quoted NSIS strings (the registry key path defines), and a quoted value would leave
stray embedded quote characters in those. `CONNECTOR_WRITE_ALLOWED_ORIGINS_JSON` is a macro, not a
`!define` string, because `allowed_origins` is a JSON ARRAY of arbitrary length (0 today -- see
identity.json's own comment on why) and NSIS's preprocessor has no clean way to hand a `!define`
a multi-element quoted-string list; emitting the exact `FileWrite` calls needed avoids relying on
any NSIS-preprocessor quoting behavior beyond plain text substitution.

Usage: python app/desktop-shell/packaging/generate_connector_nsh.py
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
IDENTITY_PATH = PROJECT_ROOT / "app" / "desktop-shell" / "connector" / "identity.json"
OUT_PATH = PROJECT_ROOT / "app" / "desktop-shell" / "src-tauri" / "windows" / "connector-identity.generated.nsh"


def main() -> None:
    identity = json.loads(IDENTITY_PATH.read_text(encoding="utf-8"))
    host_name = identity["native_host_name"]
    origins = [f"chrome-extension://{ext_id}/" for ext_id in identity["production_extension_ids"]]
    for ext_id in identity["production_extension_ids"]:
        if len(ext_id) != 32 or any(c not in "abcdefghijklmnop" for c in ext_id):
            raise SystemExit(f"identity.json: {ext_id!r} is not a valid 32-char Chrome extension id")

    lines = [
        "; GENERATED by packaging/generate_connector_nsh.py from connector/identity.json.",
        "; Do not hand-edit -- rerun the generator after changing identity.json instead.",
        "",
        f"!define CONNECTOR_NATIVE_HOST_NAME {host_name}",
        "",
        "!macro CONNECTOR_WRITE_ALLOWED_ORIGINS_JSON",
    ]
    if not origins:
        lines.append("  FileWrite $1 '[]$\\r$\\n'")
    else:
        lines.append("  FileWrite $1 '[$\\r$\\n'")
        for index, origin in enumerate(origins):
            comma = "," if index < len(origins) - 1 else ""
            lines.append(f"  FileWrite $1 '    \"{origin}\"{comma}$\\r$\\n'")
        lines.append("  FileWrite $1 '  ]$\\r$\\n'")
    lines.append("!macroend")
    lines.append("")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"generated {OUT_PATH} ({len(origins)} allowed origin(s))")


if __name__ == "__main__":
    main()
