"""Build the browser-capture connector host and stage it into resources/connector/ for bundling.

Mirrors `stage_source.py`'s own pattern: a resource Tauri's bundler copies verbatim, generated by
an explicit pre-build step. The connector host lives in its OWN Cargo package
(`app/desktop-shell/connector-host/`), never as a second `[[bin]]` inside src-tauri's own package
-- a real clean-runner build proved that having two `[[bin]]` targets in the SAME package as the
Tauri app confuses `cargo tauri build`'s main-binary selection: even with `mainBinaryName`
explicitly set, the installer ended up shipping the CONNECTOR's compiled bytes under
callosum-shell.exe's name, so the real application silently never started. See
`connector-host/Cargo.toml`'s own comment for the exact repro. A separate package removes the
ambiguity at its root: `cargo tauri build` never sees this binary exist in the package it builds.

The staged filename (`callosum-connector.exe`, hyphenated) deliberately differs from the compiled
artifact's name (`callosum_connector.exe`, Rust's binary-target convention) — this is a rename, not
an accident: it matches the desktop shell's own hyphenated naming (`callosum-shell.exe`) and the
name the installer hook and native-messaging manifest both expect.

Usage: python app/desktop-shell/packaging/stage_connector.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
CONNECTOR_HOST = PROJECT_ROOT / "app" / "desktop-shell" / "connector-host"
DEST_DIR = PROJECT_ROOT / "app" / "desktop-shell" / "resources" / "connector"
BIN_NAME = "callosum_connector"
STAGED_NAME = "callosum-connector.exe" if sys.platform == "win32" else "callosum-connector"


def main() -> None:
    subprocess.run(
        ["cargo", "build", "--release", "--manifest-path", str(CONNECTOR_HOST / "Cargo.toml")],
        check=True,
    )
    built = CONNECTOR_HOST / "target" / "release" / (f"{BIN_NAME}.exe" if sys.platform == "win32" else BIN_NAME)
    if not built.is_file():
        raise SystemExit(f"expected the connector host to be built at {built}, but it is missing")

    DEST_DIR.mkdir(parents=True, exist_ok=True)
    for stale in DEST_DIR.iterdir():
        stale.unlink()
    shutil.copy2(built, DEST_DIR / STAGED_NAME)
    print(f"staged connector host into {DEST_DIR / STAGED_NAME}")


if __name__ == "__main__":
    main()
