"""Build the browser-capture connector host and stage it for bundling.

Windows: stage into resources/connector/ (a Tauri bundle resource, installed under `$INSTDIR\\connector`).
macOS:   stage as a Tauri **external binary (sidecar)** under src-tauri/binaries/callosum-connector-<target-triple>.
         A Mach-O helper is executable code, not a resource: `bundle.resources` lands in `Contents/Resources`, whereas
         `bundle.externalBin` is Tauri's mechanism for embedding executable sidecars (and it requires the target-triple
         suffix at build time). Where Tauri actually places the sidecar in the finished .app is *observed* by the macOS
         workflow, not assumed here.
Linux:   no connector is staged (browser capture is not supported there yet; the desktop shell must still build).

Mirrors `stage_source.py`'s own pattern: generated by an explicit pre-build step. The connector host lives in its OWN
Cargo package (`app/desktop-shell/connector-host/`), never as a second `[[bin]]` inside src-tauri's own package
-- a real clean-runner build proved that having two `[[bin]]` targets in the SAME package as the
Tauri app confuses `cargo tauri build`'s main-binary selection: even with `mainBinaryName`
explicitly set, the installer ended up shipping the CONNECTOR's compiled bytes under
callosum-shell.exe's name, so the real application silently never started. See
`connector-host/Cargo.toml`'s own comment for the exact repro. A separate package removes the
ambiguity at its root: `cargo tauri build` never sees this binary exist in the package it builds.

The staged filename (`callosum-connector`, hyphenated) deliberately differs from the compiled
artifact's name (`callosum_connector`, Rust's binary-target convention) — this is a rename, not
an accident: it matches the desktop shell's own hyphenated naming (`callosum-shell`) and the
name the installer hook and native-messaging manifest both expect.

Usage: python app/desktop-shell/packaging/stage_connector.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
CONNECTOR_HOST = PROJECT_ROOT / "app" / "desktop-shell" / "connector-host"
WINDOWS_DEST_DIR = PROJECT_ROOT / "app" / "desktop-shell" / "resources" / "connector"
SIDECAR_DIR = PROJECT_ROOT / "app" / "desktop-shell" / "src-tauri" / "binaries"
BIN_NAME = "callosum_connector"
STAGED_BASE = "callosum-connector"


def staged_target(platform: str, target_triple: str | None) -> Path:
    """Where the built connector is staged for `platform` (a `sys.platform` value)."""
    if platform == "win32":
        return WINDOWS_DEST_DIR / f"{STAGED_BASE}.exe"
    if platform == "darwin":
        if not target_triple:
            raise ValueError("a macOS sidecar needs the Rust host target triple (Tauri requires the suffix)")
        return SIDECAR_DIR / f"{STAGED_BASE}-{target_triple}"
    raise ValueError(f"browser capture does not stage a connector on {platform!r}")


def host_target_triple() -> str:
    """The Rust host triple, e.g. aarch64-apple-darwin / x86_64-apple-darwin (each CI runner builds natively)."""
    out = subprocess.run(["rustc", "-vV"], capture_output=True, text=True, check=True).stdout
    for line in out.splitlines():
        if line.startswith("host:"):
            return line.split(":", 1)[1].strip()
    raise SystemExit("could not read the host target triple from `rustc -vV`")


def main() -> None:
    triple = host_target_triple() if sys.platform == "darwin" else None
    try:
        target = staged_target(sys.platform, triple)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    subprocess.run(
        ["cargo", "build", "--release", "--manifest-path", str(CONNECTOR_HOST / "Cargo.toml")],
        check=True,
    )
    built = CONNECTOR_HOST / "target" / "release" / (f"{BIN_NAME}.exe" if sys.platform == "win32" else BIN_NAME)
    if not built.is_file():
        raise SystemExit(f"expected the connector host to be built at {built}, but it is missing")

    target.parent.mkdir(parents=True, exist_ok=True)
    for stale in target.parent.iterdir():
        if stale.is_file() and (sys.platform == "win32" or stale.name.startswith(f"{STAGED_BASE}-")):
            stale.unlink()
    shutil.copy2(built, target)
    if sys.platform != "win32":
        target.chmod(0o755)
    print(f"staged connector host into {target}")


if __name__ == "__main__":
    main()
