"""Build the browser-capture connector host and stage it into resources/connector/ for bundling.

Mirrors `stage_source.py`'s own pattern: a resource Tauri's bundler copies verbatim, generated by
an explicit pre-build step rather than left to `tauri build`'s own cargo invocation, which is not
guaranteed to compile every `[[bin]]` in the crate (`mainBinaryName` binds the app to exactly one).

The staged filename (`callosum-connector.exe`, hyphenated) deliberately differs from the compiled
artifact's name (`callosum_connector.exe`, Rust's binary-target convention) — this is a rename, not
an accident: it matches the desktop shell's own hyphenated naming (`callosum-shell.exe`) and the
name the installer hook and native-messaging manifest both expect. It ships inside a `connector/`
subdirectory specifically so it can NEVER collide with the identically-plausible `callosum-connector`
name Cargo could otherwise produce directly in `target/release/` alongside the real build output.

Usage: python app/desktop-shell/packaging/stage_connector.py
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
SRC_TAURI = PROJECT_ROOT / "app" / "desktop-shell" / "src-tauri"
DEST_DIR = PROJECT_ROOT / "app" / "desktop-shell" / "resources" / "connector"
BIN_NAME = "callosum_connector"
STAGED_NAME = "callosum-connector.exe" if sys.platform == "win32" else "callosum-connector"


def main() -> None:
    # tauri-build's build script validates every `bundle.resources` source path exists on ANY
    # `cargo build` of this package -- including this very invocation, since callosum_connector is
    # a `[[bin]]` in the SAME package as the main shell. The directory must exist BEFORE the cargo
    # build below runs, or that unrelated build-script check fails the compile outright. An empty
    # directory satisfies it; the real binary is copied in afterward.
    DEST_DIR.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        ["cargo", "build", "--release", "--bin", BIN_NAME, "--manifest-path", str(SRC_TAURI / "Cargo.toml")],
        check=True,
    )
    built = SRC_TAURI / "target" / "release" / (f"{BIN_NAME}.exe" if sys.platform == "win32" else BIN_NAME)
    if not built.is_file():
        raise SystemExit(f"expected the connector host to be built at {built}, but it is missing")

    for stale in DEST_DIR.iterdir():
        stale.unlink()
    shutil.copy2(built, DEST_DIR / STAGED_NAME)
    print(f"staged connector host into {DEST_DIR / STAGED_NAME}")


if __name__ == "__main__":
    main()
