"""Build the single-file Google Docs add-on bundle (inc 193).

Concatenates the three Apps Script sources — ``gdocs_core.js`` (pure logic) + ``Code.gs`` (the add-on) +
``sidebar.html`` (inlined) — into ONE ``callosum-gdocs.gs`` the user pastes once, instead of adding three files +
naming them by hand. Apps Script runs every ``.gs`` in one global scope, so ``gdocs_core``'s
``globalThis.CallosumCore`` is visible to ``Code.gs``; the sidebar HTML is embedded as a JSON-encoded string +
served via ``HtmlService.createHtmlOutput(...)`` (no separate HTML file needed).

Run after editing any of the three sources::

    python tools/build_gdocs_addon.py

``tests/test_gdocs_bundle.py`` asserts the committed bundle stays in sync.
"""

from __future__ import annotations

import json
from pathlib import Path

ADAPTER = Path(__file__).resolve().parents[1] / "adapters" / "googledocs"
CORE = ADAPTER / "gdocs_core.js"
CODE = ADAPTER / "Code.gs"
SIDEBAR = ADAPTER / "sidebar.html"
OUTPUT = ADAPTER / "callosum-gdocs.gs"

# In the bundle the sidebar is an inline string (no separate HTML file), so the file-load becomes an inline-load.
_FILE_LOAD = 'HtmlService.createHtmlOutputFromFile("sidebar")'
_INLINE_LOAD = "HtmlService.createHtmlOutput(_callosumSidebarHtml())"

_HEADER = (
    "// GENERATED by tools/build_gdocs_addon.py — do NOT edit here.\n"
    "// Edit gdocs_core.js / Code.gs / sidebar.html, then re-run the builder.\n"
    "// To install: Google Doc → Extensions → Apps Script → select all in Code.gs, replace with THIS file → Save.\n"
)


def build() -> str:
    core = CORE.read_text(encoding="utf-8")
    code = CODE.read_text(encoding="utf-8")
    sidebar = SIDEBAR.read_text(encoding="utf-8")
    if _FILE_LOAD not in code:
        raise SystemExit(f"Expected {_FILE_LOAD!r} in Code.gs (the sidebar load) — the builder needs updating.")
    code = code.replace(_FILE_LOAD, _INLINE_LOAD)
    sidebar_fn = (
        "\n// ── sidebar.html, inlined by the bundle builder (served via HtmlService.createHtmlOutput) ──\n"
        f"function _callosumSidebarHtml() {{\n  return {json.dumps(sidebar)};\n}}\n"
    )
    return f"{_HEADER}\n{core.rstrip()}\n\n{code.rstrip()}\n{sidebar_fn}"


def main() -> int:
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes) — paste this one file into Apps Script.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
